"""
run_analysis.py
----------------
Master orchestration script.

Executes the full duplicate payment detection pipeline in order:
  1. Generate synthetic AP dataset
  2. Run detection pipeline (rule-based scoring)
  3. Run causal analysis (DiD + Chi-Square)
  4. Generate all visualizations
  5. Export summary report

Usage
-----
  python run_analysis.py
"""

import os
import sys
import json
from datetime import datetime

# ── Ensure src/ is on path when running from project root ────────────────────
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from src.generate_data      import generate_transactions, save_datasets
from src.detection_pipeline import run_pipeline
from src.causal_analysis    import run_causal_analysis
from src.visualizations     import generate_all_figures


def export_summary(did_results: dict, pipeline_metrics: dict = None):
    """Write a JSON summary of key findings to reports/."""
    os.makedirs("reports", exist_ok=True)
    summary = {
        "run_timestamp": datetime.now().isoformat(),
        "causal_analysis": {
            "did_estimate":     did_results["did"]["did_estimate"],
            "bootstrap_ci":     did_results["ci"],
            "chi_square":       {k: v for k, v in did_results["chi_square"].items()
                                 if k != "contingency_table"},
            "interpretation": (
                f"Post-migration, affected BUs experienced a "
                f"{did_results['did']['did_estimate']*100:.1f}pp increase in duplicate rate "
                f"over and above the control group trend. "
                f"This effect is {'statistically significant' if did_results['chi_square']['significant_at_5pct'] else 'not statistically significant'} "
                f"at the 5% level (p={did_results['chi_square']['p_value']})."
            ),
        },
        "sources": [
            "Synthetic data generated by src/generate_data.py",
            "DiD methodology: Angrist & Pischke (2009) — Mostly Harmless Econometrics",
            "Chi-square test: scipy.stats.chi2_contingency",
            "Bootstrap CI: 1000 iterations, 95% confidence level",
        ],
    }
    out = "reports/analysis_summary.json"
    with open(out, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\n[✓] Summary report saved → {out}")
    return summary


def main():
    print("\n" + "="*60)
    print("  Duplicate Payment Detection — Full Pipeline")
    print("="*60)

    # ── Step 1: Generate data ────────────────────────────────────────────────
    print("\n[STEP 1/4] Generating synthetic AP transaction data...")
    df = generate_transactions()
    save_datasets(df, out_dir="data")

    # ── Step 2: Detection pipeline ───────────────────────────────────────────
    print("\n[STEP 2/4] Running detection pipeline...")
    scored = run_pipeline(input_path="data/ap_transactions.csv",
                          output_dir="data")

    # ── Step 3: Causal analysis ──────────────────────────────────────────────
    print("\n[STEP 3/4] Running causal analysis (DiD + Chi-Square)...")
    results = run_causal_analysis(input_path="data/ap_transactions.csv")

    # ── Step 4: Visualizations ───────────────────────────────────────────────
    print("\n[STEP 4/4] Generating visualizations...")
    generate_all_figures(
        transactions_path="data/ap_transactions.csv",
        scored_path="data/ap_transactions_scored.csv",
        rates_df=results["group_rates"],
    )

    # ── Export summary ───────────────────────────────────────────────────────
    summary = export_summary(results)

    print("\n" + "="*60)
    print("  ALL STEPS COMPLETE")
    print("="*60)
    print("\n  Outputs:")
    print("    data/ap_transactions.csv              – raw transactions")
    print("    data/ap_transactions_pre_migration.csv")
    print("    data/ap_transactions_post_migration.csv")
    print("    data/summary_by_bu_period.csv         – aggregated rates")
    print("    data/ap_transactions_scored.csv       – detection output")
    print("    reports/fig1_monthly_trend.png")
    print("    reports/fig2_did_bars.png")
    print("    reports/fig3_category_heatmap.png")
    print("    reports/fig4_score_distribution.png")
    print("    reports/fig5_financial_exposure.png")
    print("    reports/analysis_summary.json")
    print("\n  DiD Estimate : "
          f"{results['did']['did_estimate']*100:.1f}pp causal increase in duplicate rate")
    print(f"  Chi-Square p : {results['chi_square']['p_value']}")
    print(f"  Significant  : {results['chi_square']['significant_at_5pct']}")
    print()


if __name__ == "__main__":
    main()
